image: "quay.io/openshift_sandboxed_containers/gpu-verifier@sha256:dcc55b6c51a85cda62322f7f07f5aa8d42632481254d8bf47e2e24705b245797"

runtimeClassName: "kata-cc-nvidia-gpu"

defaultMemory: "32768"

global:
  clusterPlatform: ""

# Serve only nonsecret validation results; secure policy blocks host log streaming.
resultsImage: registry.redhat.io/ubi9/httpd-24@sha256:68a91ff691092f455fea682330c499588747231c16516cd4f35aff821e6847f2
