lvmCluster:
  deviceSelector:
    paths:
      - /dev/disk/by-id/nvme-eui.01000000000000058ce38ee3034e25da

vault:
  server:
    dataStorage:
      storageClass: lvms-vg1

global:
  objectStorage:
    backingStorageClass: "lvms-vg1"
