{{- if not (eq .Values.global.coco.secured  true) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rvps-reference-values
  namespace: trustee-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    kbs.confidentialcontainers.org/migrated-from-v1.1.0: v1.2.0
data:
  reference_value: '{}'
{{ end }}